'use client';
import {useState} from 'react';
import {ArrowRight,Check,FileText,FlaskConical,Globe2,Package,Plus,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {marketNames,sources} from '@/lib/seed-data';
import type {MarketCode} from '@/lib/launchlayer-types';
import {actionNames,claimExamples,decide,decisionConsequence,evaluateClaim,issuesFor,lifecycles,makeClaim,makePlan,readiness,recordChange,type Claim,type ClaimAction,type Issue,type Product,type Section} from '@/lib/product-model';
import {Chips,Choice,MarketSelect,Panel,Pill,SourceLink} from './workspace-controls';

type Props={p:Product;save:(p:Product)=>void;go:(s:Section)=>void};
export function ProductWorkspace({p,save,section,go}:{section:Section}&Props){
  return <div className="product-workspace">
    <header className="product-heading"><div><h1>{p.name}</h1><div className="product-meta"><span>{p.kind==='new'?'New product':'Existing product'}</span><span>{p.sku||'No SKU assigned'}</span><span>Passport v{p.version}</span></div></div><Choice label="Lifecycle" value={p.lifecycle} options={lifecycles} onChange={v=>save(recordChange(p,`Lifecycle changed to ${v}.`,{lifecycle:v as Product['lifecycle']}))}/></header>
    <nav className="product-tabs" aria-label="Product workspace">{([['overview','Overview'],['markets','Markets'],['formula','Formula'],['claims','Claims & Packaging'],['launch','Launch Plan'],['activity','Activity']] as const).map(([id,label])=><button key={id} aria-current={section===id?'page':undefined} onClick={()=>go(id)}>{label}</button>)}</nav>
    {section==='overview'&&<Overview p={p} save={save} go={go}/>}
    {section==='markets'&&<Markets p={p} save={save} go={go}/>}
    {section==='formula'&&<Formula p={p} save={save} go={go}/>}
    {section==='claims'&&<ClaimsPackaging p={p} save={save} go={go}/>}
    {section==='launch'&&<LaunchPlan p={p} save={save} go={go}/>}
    {section==='activity'&&<Panel title="Version history">{p.activity.map(a=><article className="activity-row" key={a.id}><span className="version">v{a.version}</span><div><strong>{a.message}</strong><small>{new Date(a.at).toLocaleString()}</small></div></article>)}</Panel>}
  </div>;
}
function Overview({p,save,go}:Props){
  const missing=p.ingredients.length===0||p.ingredients.some(i=>!i.confirmed);
  const next=p.kind==='new'&&!p.claims.length?{label:'Review available claims',to:'claims' as Section,why:'Choose the claim directions your formula and evidence should support.'}:missing?{label:'Resolve missing formula information',to:'formula' as Section,why:'Ingredient identity and concentration must be known before a reliable assessment.'}:!p.assessed?{label:'Review missing information',to:'markets' as Section,why:'Check the supplied facts before running an assessment.'}:p.tasks.length?{label:'Continue launch preparation',to:'launch' as Section,why:'Complete linked tasks and retain evidence for final review.'}:{label:'Review market blockers',to:'markets' as Section,why:'Decide which changes will address the selected markets.'};
  return <><div className="overview-grid"><section className="next-action"><span className="small-label">Next decision</span><h2>{next.label}</h2><p>{next.why}</p><Button onClick={()=>go(next.to)}>{next.label}<ArrowRight size={16}/></Button></section><section className="panel passport-summary"><dl><div><dt>Current markets</dt><dd>{p.current.map(m=>marketNames[m]).join(', ')||'Not on market'}</dd></div><div><dt>Target markets</dt><dd>{p.markets.map(m=>marketNames[m]).join(', ')}</dd></div><div><dt>Product</dt><dd>{p.format} · {p.areas.join(', ')}</dd></div><div><dt>Intended benefit</dt><dd>{p.benefits.join(', ')}</dd></div></dl></section></div>
    <div className="readiness-grid">{p.markets.map(m=><button className="readiness-card" onClick={()=>go('markets')} key={m}><div><span className="country-code">{m}</span><h3>{marketNames[m]}</h3></div><Pill>{p.assessed?readiness(p,m):'Not assessed'}</Pill><p>{issuesFor(p,m).length} unresolved findings · {p.assessed?'Medium':'Low'} confidence</p></button>)}</div>
    <div className="status-grid">{[{title:'Formula',value:p.ingredients.length?`${p.ingredients.length} ingredients · ${missing?'information missing':'candidate entered'}`:'Candidate needed',to:'formula',icon:FlaskConical},{title:'Claims',value:`${p.claims.filter(c=>!c.removed).length} active claims`,to:'claims',icon:FileText},{title:'Packaging',value:p.packaging?'Draft label entered':'Candidate needed',to:'claims',icon:Package},{title:'Launch plan',value:p.tasks.length?`${p.tasks.filter(t=>t.done).length}/${p.tasks.length} tasks complete`:'Strategy not selected',to:'launch',icon:Globe2}].map(x=><button key={x.title} onClick={()=>go(x.to as Section)}><x.icon size={18}/><strong>{x.title}</strong><span>{x.value}</span><ArrowRight size={14}/></button>)}</div>
    {p.kind==='new'&&<DesignBrief p={p} go={go}/>}
    <details className="panel"><summary>Product decisions</summary><div className="decision-fields"><div className="form-pair"><Choice label="Formula strategy" value={p.formulaStrategy} options={['Global','Regional']} onChange={v=>save(recordChange(p,`Formula strategy: ${v}.`,{formulaStrategy:v as Product['formulaStrategy']}))}/><Choice label="Packaging strategy" value={p.packagingStrategy} options={['Universal','Regional']} onChange={v=>save(recordChange(p,`Packaging strategy: ${v}.`,{packagingStrategy:v as Product['packagingStrategy']}))}/></div><Chips label="Evidence and testing work" value={p.evidenceWork} options={['Safety assessment','Stability','Packaging compatibility','Consumer perception','Instrumental performance']} onChange={v=>save(recordChange(p,'Updated evidence and testing work.',{evidenceWork:v}))}/></div></details>
  </>;
}
function DesignBrief({p,go}:{p:Product;go:(s:Section)=>void}){
  return <section className="design-brief"><div className="section-line"><h2>Global design brief</h2><span>Original concept · {p.markets.join(' / ')}</span></div><div className="brief-grid">
    <Panel title="Available claims" action={<button className="text-link" onClick={()=>go('claims')}>Choose directions <ArrowRight size={14}/></button>}><ul><li><strong>Shared territory:</strong> hydration, softness, smoother-looking texture; substantiate the finished product.</li><li><strong>Evidence required:</strong> visible fine-line, bounce and radiance performance.</li>{p.markets.includes('JP')&&<li><strong>Japan opportunity:</strong> localized cosmetic radiance wording; melanin-inhibition positioning needs pathway review.</li>}<li><strong>Classification risk:</strong> repair of damaged tissue, regeneration and collagen stimulation.</li><li><strong>Avoid:</strong> unsupported absolute or clinical claims. Prefer “helps skin look…” wording.</li></ul></Panel>
    <Panel title="Packaging requirements" action={<button className="text-link" onClick={()=>go('claims')}>Review package <ArrowRight size={14}/></button>}><ul><li><strong>Universal baseline:</strong> identity, ingredients, net contents, batch reference, directions and responsible-company information.</li>{p.markets.includes('US')&&<li><strong>US:</strong> English labeling, business/contact details and applicable warnings.</li>}{p.markets.includes('EU')&&<li><strong>EU:</strong> Responsible Person, durability/PAO as applicable, warnings, INCI and destination-language checks.</li>}{p.markets.includes('JP')&&<li><strong>Japan:</strong> Japanese ingredient names, local-company information, required Japanese label text and applicable expiry.</li>}<li><strong>Shared package:</strong> potentially feasible with a localized panel; final copy and space need verification.</li></ul></Panel>
    <Panel title="Formula boundaries" action={<button className="text-link" onClick={()=>go('formula')}>Build candidate <ArrowRight size={14}/></button>}><ul><li><strong>Avoid:</strong> prohibited substances and unconfirmed trade blends.</li><li><strong>Sample corridor:</strong> phenoxyethanol ≤1% where EU/Japan selected; source annex conditions still apply.</li><li><strong>Restricted:</strong> retinoids require identity, concentration and warning review; no universal limit inferred.</li><li><strong>Use restrictions:</strong> {p.areas.includes('Eye contour')?'Eye-area exposure requires specific safety review.':'Leave-on face use; do not generalize to mucosal or eye exposure.'}</li><li><strong>Collect:</strong> supplier composition, CoA, impurities; safety, stability and compatibility evidence.</li></ul></Panel>
    <Panel title="Launch obligations" action={<button className="text-link" onClick={()=>go('launch')}>Plan work <ArrowRight size={14}/></button>}><ul>{p.markets.includes('US')&&<li><strong>US:</strong> review applicable MoCRA listing/registration, safety substantiation and adverse-event obligations.</li>}{p.markets.includes('EU')&&<li><strong>EU:</strong> Responsible Person, PIF/CPSR, GMP and CPNP notification.</li>}{p.markets.includes('JP')&&<li><strong>Japan:</strong> appropriate local party, import arrangements, cosmetic notification or quasi-drug marketing approval pathway.</li>}<li><strong>All selected markets:</strong> manufacturing records, final safety documentation and post-market complaint handling.</li></ul></Panel>
  </div><div className="brief-sources">{p.markets.map(m=><SourceLink key={m} id={m==='US'?'SRC-US-01':m==='EU'?'SRC-EU-01':'SRC-JP-02'}/>)}</div></section>;
}
function Markets({p,save,go}:Props){
  const [issue,setIssue]=useState<(Issue&{market:MarketCode})|null>(null);
  const [selected,setSelected]=useState('Global adaptation');
  const [scope,setScope]=useState(p.markets);const [current,setCurrent]=useState(p.current);
  const missing=p.markets.flatMap(m=>issuesFor(p,m).filter(i=>i.status==='Insufficient information').map(i=>`${m}: ${i.title}`));
  function assess(){save(recordChange(p,'Reviewed missing information and ran the seeded market assessment.',{reviewed:true,assessed:true,validatedVersion:p.version+1}));}
  return <><div className="section-line"><p>{p.assessed?'Readiness recalculates as product facts and claim decisions change.':'Review missing information before running the first assessment.'}</p><Button onClick={assess}>{p.assessed?'Revalidate product':'Run market assessment'}</Button></div>
    <details className="panel"><summary>Current and target markets</summary><div className="decision-fields"><MarketSelect label="Current markets" value={current} onChange={setCurrent}/><MarketSelect value={scope} onChange={setScope}/><Button disabled={!scope.length} onClick={()=>save(recordChange(p,'Updated market scope; assessment needs revalidation.',{markets:scope,current,assessed:false}))}>Save market scope</Button></div></details>
    {missing.length>0&&<Panel title="Missing or ambiguous information"><ul className="compact-list">{missing.map(x=><li key={x}>{x}</li>)}</ul><p className="muted">The assessment retains these gaps and cannot return an unqualified Ready status.</p></Panel>}
    <div className="readiness-grid">{p.markets.map(m=><section className="panel" key={m}><div className="country-title"><span className="country-code">{m}</span><h2>{marketNames[m]}</h2></div><Pill>{p.assessed?readiness(p,m):'Not assessed'}</Pill><p className="muted">{missing.length?'Low':'Medium'} confidence · passport v{p.version}</p><div className="issue-buttons">{issuesFor(p,m).map(i=><button key={i.id} onClick={()=>setIssue({...i,market:m})}><span>{i.title}</span><ArrowRight size={14}/></button>)}</div></section>)}</div>
    <Panel title="Expansion strategies"><p className="muted">Preview claim changes without inventing supplier confirmations or completed administrative work.</p><div className="strategy-options">{['No change','Global adaptation','Regional variants'].map(strategy=>{
      let candidate=p;
      if(strategy!=='No change')candidate={...p,claims:p.claims.map(c=>({...c,decisions:Object.fromEntries(p.markets.map(m=>[m,{action:'Accept recommended wording' as ClaimAction,wording:evaluateClaim(c,m).alternative,note:'Strategy preview',at:''}]))}))};
      const removed=p.markets.reduce((n,m)=>n+issuesFor(p,m).length-issuesFor(candidate,m).length,0);
      return <button className="strategy-option" aria-pressed={selected===strategy} key={strategy} onClick={()=>setSelected(strategy)}><strong>{strategy}</strong><small>{strategy==='No change'?'Low effort · current product':strategy==='Global adaptation'?'Medium effort · one wording master':'Higher effort · localized claim versions'}</small><p>{strategy==='No change'?'Keeps all current findings.':`${removed} sample findings potentially resolved by appearance-focused wording.`}</p>{p.markets.map(m=><div key={m}><b>{m}</b><span>{readiness({...candidate,assessed:true},m)}</span></div>)}</button>;
    })}</div><p className="inline-note">Formula uncertainty, evidence, localization, packaging and market-entry obligations remain. Strategy selection generates work; it does not mark it complete.</p><Button onClick={()=>{save(makePlan(p,selected));go('launch');}}>Generate launch plan · {selected}</Button></Panel>
    <Sheet open={!!issue} onOpenChange={v=>!v&&setIssue(null)}><SheetContent className="finding-sheet">{issue&&<><SheetHeader><SheetTitle>{issue.title}</SheetTitle><SheetDescription>{marketNames[issue.market]} · {issue.dimension} · Demonstration finding</SheetDescription></SheetHeader><div className="sheet-body"><Pill>{issue.status}</Pill><dl className="detail-list"><dt>Why it matters</dt><dd>{issue.why}</dd><dt>Recommended action</dt><dd>{issue.action}</dd><dt>Consequence</dt><dd>Updates the linked product facts or decision. Other country findings remain until separately addressed; revalidation retains unresolved evidence and operational requirements.</dd><dt>Information type</dt><dd>{issue.type}</dd><dt>Source / version</dt><dd><SourceLink id={issue.source}/>{sources.find(s=>s.id===issue.source)?.version}</dd><dt>Effective date</dt><dd>{issue.type==='Legal requirement'?'See the cited provision; source seed dates are not verified currency guarantees.':'Not applicable to sample product recommendations.'}</dd><dt>Confidence / reviewed</dt><dd>Medium · source seed snapshot September 2026</dd></dl><Button onClick={()=>{go(issue.target);setIssue(null);}}>Resolve in {issue.target==='claims'?'Claims & Packaging':issue.target==='formula'?'Formula':'Launch Plan'}<ArrowRight size={15}/></Button></div></>}</SheetContent></Sheet>
  </>;
}
const ingredientOptions=['Aqua','Glycerin','Niacinamide','Squalane','Retinol','Retinol Complex','Phenoxyethanol'];
function Formula({p,save,go}:Props){
  const [draft,set]=useState(p.ingredients);const [ingredient,setIngredient]=useState('Glycerin');const [error,setError]=useState('');
  const [manufacturer,setManufacturer]=useState(p.manufacturer);
  function commit(){if(draft.some(i=>i.concentration===''||!Number.isFinite(Number(i.concentration))||Number(i.concentration)<0||Number(i.concentration)>100)){setError('Each concentration must be a number from 0 to 100.');return;}save(recordChange(p,'Saved candidate formula and manufacturing information; revalidation required.',{ingredients:draft,manufacturer,validatedVersion:null}));setError('');}
  return <><div className="section-line"><p>Enter the candidate formula and supplier-confirmed ingredient identities.</p><Button onClick={commit}>Save candidate formula</Button></div>
    <Panel title="Formula candidate"><div className="ingredient-add"><Choice label="Ingredient" value={ingredient} options={ingredientOptions} onChange={setIngredient}/><Button variant="outline" onClick={()=>{if(!draft.some(i=>i.name===ingredient))set([...draft,{name:ingredient,concentration:'',confirmed:false}]);}}><Plus size={15}/>Add ingredient</Button></div>
      <div className="formula-grid heading"><span>Ingredient</span><span>Concentration %</span><span>Identity confirmed</span><span/></div>{draft.map((i,n)=><div className="formula-grid" key={i.name}><strong>{i.name}</strong><Input aria-label={`${i.name} concentration`} type="number" min="0" max="100" step="0.01" value={i.concentration} onChange={e=>set(draft.map((x,k)=>k===n?{...x,concentration:e.target.value}:x))}/><label className="check-label"><Checkbox aria-label={`Confirm ${i.name} identity`} checked={i.confirmed} onCheckedChange={v=>set(draft.map((x,k)=>k===n?{...x,confirmed:v===true}:x))}/><span>Supplier confirmed</span></label><Button variant="ghost" size="icon" aria-label={`Remove ${i.name}`} onClick={()=>set(draft.filter((_,k)=>k!==n))}><Trash2 size={15}/></Button></div>)}{!draft.length&&<p className="empty">Add an ingredient or import a CSV with name,concentration columns.</p>}<p className="muted">Total: {draft.reduce((n,i)=>n+(Number(i.concentration)||0),0).toFixed(2)}% · confirmation requires supplier documentation.</p>{error&&<p role="alert" className="error">{error}</p>}</Panel>
    <Upload p={p} save={save} kind="formula" onText={text=>{const rows=text.split(/\r?\n/).filter(Boolean).map(l=>l.split(','));const ingredients=rows.filter(r=>r[0].toLowerCase()!=='name').map(r=>({name:r[0].trim(),concentration:(r[1]??'').replace('%','').trim(),confirmed:false}));set(ingredients);}}/>
    <Panel title="Formula boundaries"><div className="form-pair"><Chips label="Ingredient preferences" value={p.preferences} options={['Fragrance-free','Retinoid-free','Minimal formula']} onChange={v=>save(recordChange(p,'Updated ingredient preferences.',{preferences:v}))}/><Chips label="Ingredients to avoid" value={p.avoid} options={ingredientOptions.filter(x=>x!=='Aqua')} onChange={v=>save(recordChange(p,'Updated ingredients to avoid.',{avoid:v}))}/></div><ul className="compact-list"><li>Sample phenoxyethanol boundary: ≤1% for selected EU/Japan markets; concentration and use conditions need verification.</li><li>Retinoids: confirm active identity, concentration, required warnings and applicable annex conditions. No automatic clearance.</li><li>{p.areas.includes('Eye contour')?'Eye contour selected: specific eye-area safety review required.':'Scope is adult leave-on facial skincare; other exposure conditions require review.'}</li><li>Collect supplier composition, impurity specifications, CoA, stability and final-product safety evidence.</li></ul><SourceLink id={p.markets.includes('EU')?'SRC-EU-01':p.markets.includes('JP')?'SRC-JP-01':'SRC-US-01'}/></Panel>
    <Panel title="Manufacturing information"><label className="field">Manufacturer and site notes<Textarea value={manufacturer} onChange={e=>setManufacturer(e.target.value)} placeholder="Supplier name, site, quality documentation…"/></label><Upload p={p} save={save} kind="manufacturing"/></Panel><Button variant="outline" onClick={()=>go('markets')}>Review missing information<ArrowRight size={15}/></Button>
  </>;
}
export function Upload({p,save,kind,onText}:{p:Product;save:(p:Product)=>void;kind:Product['attachments'][number]['kind'];onText?:(s:string)=>void}){
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function add(file:File){
    if(file.size>2*1024*1024){setError('Use a file smaller than 2 MB in this local demo.');return;}
    setBusy(true);setError('');
    try{
      const text=/\.(txt|csv)$/i.test(file.name);const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});
      if(text&&onText)onText(await file.text());
      save(recordChange(p,`Attached ${file.name} for ${kind}${text?'; text imported into editor':' — manual review required'}.`,{attachments:[...p.attachments,{id:crypto.randomUUID(),name:file.name,kind,mime:file.type,data,manual:!text}]}));
    }catch{setError('Could not read the file. Your current entries are preserved.');}finally{setBusy(false);}
  }
  return <div className="upload-block"><label className="field">Attach {kind}<Input aria-label={`Upload ${kind}`} type="file" accept=".csv,.txt,.pdf,.png,.jpg,.jpeg" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void add(f);}}/></label><small>CSV/text can populate editors. PDF/images are retained for manual review, with no automatic clearance.</small>{error&&<p className="error" role="alert">{error}</p>}{p.attachments.filter(a=>a.kind===kind).map(a=><div className="attachment" key={a.id}><FileText size={15}/><a href={a.data} download={a.name}>{a.name}</a><Pill>{a.manual?'Manual review needed':'Attached'}</Pill></div>)}</div>;
}
function ClaimsPackaging({p,save}:Props){
  const [selected,setSelected]=useState(p.claims.find(c=>!c.removed)?.id??'');const [market,setMarket]=useState<MarketCode>(p.markets[0]);const [mode,setMode]=useState('Claims');
  const [custom,setCustom]=useState('');const [pack,setPack]=useState(p.packaging);
  const c=p.claims.find(c=>c.id===selected&&!c.removed);
  function add(example:string){const claim=makeClaim(example);save(recordChange(p,`Added claim direction: ${claim.example}.`,{claims:[...p.claims,claim]}));setSelected(claim.id);}
  return <><div className="section-line"><div className="segmented">{['Claims','Packaging'].map(x=><button key={x} aria-pressed={mode===x} onClick={()=>setMode(x)}>{x}</button>)}</div><p>{mode==='Claims'?'Choose a phrase, country and explicit action.':'Validate candidate packaging against the original market brief.'}</p></div>
    {mode==='Claims'?<><div className="claims-workbench"><section className="panel claims-index"><h2>Product claims</h2>{p.claims.filter(x=>!x.removed).map(claim=><button className="claim-pick" key={claim.id} aria-pressed={claim.id===selected} onClick={()=>setSelected(claim.id)}><strong>{claim.text}</strong><span>{p.markets.map(m=><small key={m}>{m}: {evaluateClaim(claim,m).status}</small>)}</span></button>)}{!p.claims.some(x=>!x.removed)&&<p className="empty">Choose a direction below to start.</p>}<details open={!p.claims.length}><summary>Available claim directions</summary><div className="direction-list">{claimExamples.map(([label,text])=><button key={label} onClick={()=>add(label)}><Plus size={14}/><span><strong>{label}</strong><small>{text}</small></span></button>)}</div></details><label className="field">Custom claim text<Input value={custom} onChange={e=>setCustom(e.target.value)}/></label><Button variant="outline" disabled={!custom.trim()} onClick={()=>{add(custom);setCustom('');}}>Add custom claim</Button></section>
    <div>{c?<ClaimDecision key={`${c.id}-${market}-${p.version}`} p={p} claim={c} market={market} setMarket={setMarket} save={save}/>:<section className="panel empty">Select a product claim or choose a direction to inspect its market consequences.</section>}</div></div>
    {p.markets.includes('JP')&&<JapanPathways p={p} save={save}/>}
    <Panel title="Evidence and testing"><Chips label="Work to undertake" value={p.evidenceWork} options={['Safety assessment','Stability','Packaging compatibility','Consumer perception','Instrumental performance']} onChange={v=>save(recordChange(p,'Updated evidence work.',{evidenceWork:v}))}/><Upload p={p} save={save} kind="evidence"/></Panel></>:<><Panel title="Candidate packaging"><div className="form-pair"><label className="field">Label text<Textarea className="large-textarea" value={pack} onChange={e=>setPack(e.target.value)}/></label><div><Choice label="Packaging strategy" value={p.packagingStrategy} options={['Universal','Regional']} onChange={v=>save(recordChange(p,`Packaging strategy: ${v}.`,{packagingStrategy:v as Product['packagingStrategy']}))}/><Upload p={p} save={save} kind="packaging" onText={setPack}/></div></div><Button onClick={()=>save(recordChange(p,'Saved candidate label and validated against the original brief; manual artwork review remains.',{packaging:pack,validatedVersion:p.version+1,assessed:true}))}>Save and validate package</Button></Panel><Panel title="Packaging requirements"><p className="inline-note">{p.packagingStrategy==='Universal'?'A shared package may be feasible with localized panels.':'Country-specific artwork must be reviewed against each market.'} Final warnings, language and space require specialist validation.</p><ul className="compact-list"><li>Universal baseline: identity/function, ingredients, quantity, batch, directions, applicable durability and warnings.</li>{p.markets.includes('US')&&<li>US: English labeling; business/contact details and applicable MoCRA label obligations.</li>}{p.markets.includes('EU')&&<li>EU: Responsible Person details, INCI, applicable durability/PAO and Member State language requirements.</li>}{p.markets.includes('JP')&&<li>Japan: Japanese names and language, local-company information, batch and applicable expiry.</li>}</ul>{p.markets.map(m=><div className="package-check" key={m}><strong>{marketNames[m]}</strong><Pill>{p.packaging&&/\d+\s*(ml|g)\b/i.test(p.packaging)?'Net contents detected; manual review remains':'Net contents missing or undetected'}</Pill><SourceLink id={m==='US'?'SRC-US-01':m==='EU'?'SRC-EU-01':'SRC-JP-02'}/></div>)}</Panel></>}
  </>;
}
function ClaimDecision({p,claim,market,setMarket,save}:{p:Product;claim:Claim;market:MarketCode;setMarket:(m:MarketCode)=>void;save:(p:Product)=>void}){
  const r=evaluateClaim(claim,market);const [action,setAction]=useState<ClaimAction>('Accept recommended wording');const [wording,setWording]=useState(r.alternative);const [note,setNote]=useState('');const [context,setContext]=useState(claim.context);const [exact,setExact]=useState(claim.text);const [error,setError]=useState('');
  return <Panel title="Claim intelligence"><div className="country-switch" aria-label="Claim country">{p.markets.map(m=><button key={m} aria-pressed={m===market} onClick={()=>setMarket(m)}>{marketNames[m]}</button>)}</div><div className="exact-claim"><q>{r.wording}</q><Pill>{r.status}</Pill></div><p className="advisory-label">Sample advisory intelligence · {r.confidence} confidence</p>
    <details><summary>Full phrase and presentation context</summary><div className="decision-fields"><label className="field">Exact claim<Input value={exact} onChange={e=>setExact(e.target.value)}/></label><label className="field">Product name, neighboring words, ingredient callouts, imagery, testimonials, website copy<Textarea value={context} onChange={e=>setContext(e.target.value)}/></label><Button variant="outline" disabled={!exact.trim()} onClick={()=>save(recordChange(p,'Updated full claim and presentation context; prior claim decisions require review.',{claims:p.claims.map(c=>c.id===claim.id?{...c,text:exact,context,decisions:{}}:c)}))}>Save context and re-evaluate</Button></div></details>
    <dl className="intelligence"><dt>Classification interpretation</dt><dd>{r.impact}<p>{r.why}</p><small>Product recommendation · sample advisory intelligence, not legislation.</small></dd><dt>Official regulatory basis</dt><dd><Pill>{market==='EU'?'Legal requirement':'Official guidance'}</Pill><SourceLink id={r.source}/><p>{r.provision}</p><small>Effective date: {r.effective}. Seed version 2026.09; validate source currency before release.</small></dd><dt>Enforcement intelligence</dt><dd>No case-specific enforcement record is used in this demo. No enforcement pattern is presented as law.</dd><dt>Industry recommendation</dt><dd>Review the complete presentation, translations and finished-product substantiation together. <small>Sample advisory intelligence · ADV-CLAIMS-v2</small></dd><dt>Evidence requirement</dt><dd>{r.evidence}</dd></dl>
    <div className="decision-box"><h3>Choose an action</h3><Choice label="Claim action" value={action} options={actionNames} onChange={v=>setAction(v as ClaimAction)}/>{['Accept recommended wording','Create a country-specific version'].includes(action)&&<label className="field">Suggested alternative wording<Textarea value={wording} onChange={e=>setWording(e.target.value)}/></label>}{action==='Keep current wording and accept risk'&&<label className="field">Risk rationale <small>Required</small><Textarea value={note} onChange={e=>setNote(e.target.value)}/></label>}<div className="consequence"><strong>What happens next</strong><p>{decisionConsequence(action,market)}</p></div>{error&&<p role="alert" className="error">{error}</p>}<Button onClick={()=>{try{save(decide(p,claim.id,market,action,wording,note));}catch(e){setError((e as Error).message);}}}>Apply decision · {market}</Button></div>{claim.decisions[market]&&<p className="saved-decision"><Check size={15}/>Saved: {claim.decisions[market]!.action}</p>}
  </Panel>;
}
function JapanPathways({p,save}:{p:Product;save:(p:Product)=>void}){
  return <Panel title="Japan: choose a brightening pathway"><p className="muted">“Brighten” alone does not determine the pathway; exact efficacy, formula and presentation matter.</p><div className="pathway-grid"><article><h3>Remain a cosmetic</h3><ul><li>Appearance-focused radiance or brightness wording.</li><li>Lower relative regulatory burden; more limited efficacy positioning.</li><li>Exact Japanese wording and evidence still require validation.</li></ul><Button variant={p.pathway==='Cosmetic'?'default':'outline'} onClick={()=>save(recordChange(p,'Selected cosmetic pathway for Japan; localization still required.',{pathway:'Cosmetic'}))}>{p.pathway==='Cosmetic'?'Selected · Cosmetic':'Choose cosmetic pathway'}</Button></article><article><h3>Quasi-drug marketing approval pathway</h3><ul><li>Eligible active ingredient and approved efficacy direction.</li><li>Appropriate Japanese marketing authorization holder.</li><li>Quality, efficacy, safety documentation and marketing-approval process.</li><li>Greater relative effort, with potentially stronger permitted positioning.</li></ul><Button variant="outline" onClick={()=>{const next=recordChange(p,'Selected Japan quasi-drug marketing approval planning; no approval has been obtained.',{pathway:'Quasi-drug'});const id='jp-pathway';save({...next,tasks:next.tasks.some(t=>t.id===id)?next.tasks:[...next.tasks,{id,title:'Scope quasi-drug active, efficacy, MAH and marketing-approval dossier',market:'JP',source:'SRC-JP-02',owner:'Unassigned',due:'',done:false,dependency:'Qualified Japan pathway review',version:next.version}]});}}>{p.pathway==='Quasi-drug'?'Selected · Approval planning':'Plan quasi-drug pathway'}</Button></article></div><p className="advisory-label">Sample pathway comparison · relative effort only · no cost or timing forecast</p><SourceLink id="SRC-JP-02"/></Panel>;
}
function LaunchPlan({p,save,go}:Props){
  return <><div className="section-line"><p>{p.strategy?`${p.strategy} · ${p.tasks.filter(t=>t.done).length}/${p.tasks.length} tasks complete`:'Select an expansion strategy to generate the product’s tasks.'}</p><Button onClick={()=>{if(!p.strategy)go('markets');else save(makePlan(p,p.strategy));}}>{p.strategy?'Refresh tasks from findings':'Choose expansion strategy'}</Button></div>
    <Panel title="Launch tasks">{!p.tasks.length&&<p className="empty">No plan yet. Claims decisions can also create linked evidence or pathway tasks.</p>}{p.tasks.map(t=><article className="launch-task" key={t.id}><Checkbox aria-label={`Complete ${t.title}`} checked={t.done} onCheckedChange={v=>save(recordChange(p,`${v?'Completed':'Reopened'} task: ${t.title}. Regulatory findings require separate validation.`,{tasks:p.tasks.map(x=>x.id===t.id?{...x,done:v===true}:x)}))}/><div><strong>{t.title}</strong><small>{t.market} · Product v{t.version} · Dependency: {t.dependency}</small><SourceLink id={t.source}/><div className="task-fields"><Choice label={`Owner for ${t.id}`} value={t.owner} options={['Unassigned','Regulatory','Formulation','Brand','Packaging','Operations']} onChange={v=>save(recordChange(p,`Assigned ${t.title} to ${v}.`,{tasks:p.tasks.map(x=>x.id===t.id?{...x,owner:v}:x)}))}/><label className="field">Due date<Input aria-label={`Due date for ${t.id}`} type="date" value={t.due} onChange={e=>save(recordChange(p,'Updated task due date.',{tasks:p.tasks.map(x=>x.id===t.id?{...x,due:e.target.value}:x)}))}/></label></div></div></article>)}</Panel><div className="release-note"><strong>Release review required</strong><p>Task completion is not regulatory clearance. Final formula, artwork, evidence, local parties and unresolved country findings still require review.</p></div>
  </>;
}
