import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const demoWorkspace = sqliteTable('demo_workspace', {id:text('id').primaryKey(), payload:text('payload').notNull(), revision:integer('revision').notNull().default(0)});

export const workspaces = sqliteTable("workspaces", { id: text("id").primaryKey(), name: text("name").notNull(), createdAt: text("created_at").notNull() });
export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull(), displayName: text("display_name").notNull() }, (table) => [uniqueIndex("idx_users_email").on(table.email)]);
export const memberships = sqliteTable("memberships", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), userId: text("user_id").notNull().references(() => users.id), role: text("role").notNull() }, (table) => [index("idx_memberships_workspace_user").on(table.workspaceId, table.userId)]);
export const products = sqliteTable("products", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), name: text("name").notNull(), sku: text("sku").notNull(), stage: text("stage").notNull(), category: text("category").notNull(), createdAt: text("created_at").notNull() }, (table) => [uniqueIndex("idx_products_workspace_sku").on(table.workspaceId, table.sku)]);
export const productVersions = sqliteTable("product_versions", { id: text("id").primaryKey(), productId: text("product_id").notNull().references(() => products.id), version: text("version").notNull(), factsJson: text("facts_json").notNull(), createdAt: text("created_at").notNull() }, (table) => [uniqueIndex("idx_product_versions_product_version").on(table.productId, table.version)]);
export const formulaIngredients = sqliteTable("formula_ingredients", { id: text("id").primaryKey(), productVersionId: text("product_version_id").notNull().references(() => productVersions.id), originalName: text("original_name").notNull(), standardizedName: text("standardized_name"), functionName: text("function_name"), concentrationPpm: integer("concentration_ppm"), identityConfirmed: integer("identity_confirmed", { mode: "boolean" }).notNull().default(false) }, (table) => [index("idx_formula_ingredients_product_version").on(table.productVersionId)]);
export const regulatorySources = sqliteTable("regulatory_sources", { id: text("id").primaryKey(), jurisdiction: text("jurisdiction").notNull(), authority: text("authority").notNull(), title: text("title").notNull(), url: text("url").notNull(), version: text("version").notNull(), effectiveDate: text("effective_date").notNull(), reviewedDate: text("reviewed_date").notNull() }, (table) => [index("idx_sources_jurisdiction").on(table.jurisdiction)]);
export const rules = sqliteTable("rules", { id: text("id").primaryKey(), sourceId: text("source_id").notNull().references(() => regulatorySources.id), jurisdiction: text("jurisdiction").notNull(), dimension: text("dimension").notNull(), conditionJson: text("condition_json").notNull(), outcomeJson: text("outcome_json").notNull(), effectiveFrom: text("effective_from").notNull(), effectiveTo: text("effective_to") }, (table) => [index("idx_rules_jurisdiction_effective").on(table.jurisdiction, table.effectiveFrom)]);
export const assessments = sqliteTable("assessments", { id: text("id").primaryKey(), productVersionId: text("product_version_id").notNull().references(() => productVersions.id), market: text("market").notNull(), status: text("status").notNull(), confidence: text("confidence").notNull(), assessedAt: text("assessed_at").notNull() }, (table) => [index("idx_assessments_product_market").on(table.productVersionId, table.market)]);
export const findings = sqliteTable("findings", { id: text("id").primaryKey(), assessmentId: text("assessment_id").notNull().references(() => assessments.id), sourceId: text("source_id").notNull().references(() => regulatorySources.id), ruleId: text("rule_id").references(() => rules.id), dimension: text("dimension").notNull(), severity: text("severity").notNull(), status: text("status").notNull(), title: text("title").notNull(), explanation: text("explanation").notNull(), triggerFact: text("trigger_fact").notNull(), action: text("action").notNull(), confidence: text("confidence").notNull() }, (table) => [index("idx_findings_assessment_status").on(table.assessmentId, table.status)]);
export const launchPlans = sqliteTable("launch_plans", { id: text("id").primaryKey(), productVersionId: text("product_version_id").notNull().references(() => productVersions.id), strategy: text("strategy").notNull(), status: text("status").notNull(), createdAt: text("created_at").notNull() });
export const tasks = sqliteTable("tasks", { id: text("id").primaryKey(), launchPlanId: text("launch_plan_id").notNull().references(() => launchPlans.id), findingId: text("finding_id").references(() => findings.id), title: text("title").notNull(), workstream: text("workstream").notNull(), owner: text("owner").notNull(), dueDate: text("due_date"), country: text("country").notNull(), status: text("status").notNull(), dependencyId: text("dependency_id") }, (table) => [index("idx_tasks_plan_status").on(table.launchPlanId, table.status)]);
export const auditEvents = sqliteTable("audit_events", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), action: text("action").notNull(), payloadJson: text("payload_json").notNull(), createdAt: text("created_at").notNull() }, (table) => [index("idx_audit_entity").on(table.entityType, table.entityId)]);
